import SupabaseProvider from '@/providers/SupabaseProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import UserProvider from '@/providers/UserProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SupabaseProvider>
        <UserProvider>
          <body className={inter.className}>{children}</body>
        </UserProvider>
      </SupabaseProvider>
    </html>
  )
}
